name: Windows Build

on:
  push:
  pull_request:

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-latest

    strategy:
      matrix:
        build-args:
          [
            --locked --no-default-features,
            --locked,
            --locked --features metrics_process,
          ]

    steps:
      - uses: actions/checkout@v3
      
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
          
      - name: Build
        run: cargo build ${{ matrix.build-args }} --all
        
      - name: Test
        run: cargo test ${{ matrix.build-args }} --all
        
      - name: Clippy
        run: cargo clippy -- -D warnings
